defaults:
  - _self_
  - model: dnn.yaml
  - strategy: fedavg.yaml
  - config_fit: lstm_config_fit.yaml

PROJECT_PATH: '/workspace/fed_iomt/dataset'

hydra:
  run:
    dir: '${PROJECT_PATH}/models/hydra/static_string'

dataset:
  dataset_name: 'iomt_traffic'
  data_file_name: 'cic_ids_2017.csv.bz2'
  label_name: 'Label'
  n_features: 78

data_config:
  folder_name: '${PROJECT_PATH}/data/${dataset.dataset_name}'
  file_name: '${PROJECT_PATH}/data/${dataset.dataset_name}/${dataset.data_file_name}'
  label_name: ${dataset.label_name}
  sample_size: 20000
  n_features: ${dataset.n_features}
  label_encoding_type: 'label_encoding'
  alpha: 0.3

strategy_name: 'FedAvg'

fed_config:
  clients: ['client1', 'client2', 'client3', 'client4', 'client5', 'client6', 'client7', 'client8', 'client9', 'client10']
  server_address: "127.0.0.1:8085"
  client_name: ''
  num_rounds: 80
  num_clients: 10
  fed_strategy: ${strategy_name}
  num_clients_per_round_fit: 10
  num_clients_per_round_eval: 10
  fraction_fit: 1
  fraction_eval: 1
  num_cpus: 8
  num_gpus: 1
  train_batch_size: 512
  num_client_local_rounds: 10
  epochs: 5
  learning_rate: 0.004
  model_results_path: '${PROJECT_PATH}/models/${dataset.dataset_name}/${dataset.label_name}'

seed: 42
